version: "3"
services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - "38091:8081"
    volumes:
      - ./nexus-data:/nexus-data
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
    restart: always
