version: '3'
services:
  mongo:
    container_name: futurever-mongodb
    restart: always
    image: futurever/mongo:3.6.3
    command: mongod --replSet rs1 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
    ports:
      - "0.0.0.0:27017:27017" 
    volumes:
      - /data/mongo/db:/data/db
      - /data/mongo/configdb:/data/configdb
      #- /data/mongo/mongod.conf:/etc/mongod.conf.orig

