version: '3.1'

services:
  redis-4.0.11:
    container_name: futurever-redis-4.0.11
    image: futurever/redis:4.0.11
    command: ["redis-server", "--appendonly", "yes"]
    # hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./conf/redis.conf:/etc/redis.conf
