version: '3'
services:
  grafana:
    container_name: futurever-grafana-5.1
    restart: always
    image: futurever/grafana:5.1.0
    # environment: 
      # - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - /data/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - /data/grafana/log:/var/log/grafana
      # - /data/grafana/data:/var/lib/grafana # permissions issues
      # - /data/grafana/plugins:/var/lib/grafana/plugins
    command: -config /etc/grafana/grafana.ini
