version: '3'
services:
  influxdb:
    container_name: futurever-grafana-influxdb
    restart: always
    image: futurever/influxdb:1.5.1
    environment: 
      - INFLUXDB_BIND_ADDRESS=0.0.0.0:9088  #RPC service for backup and restore
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_REALM=InfluxDB
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=inifluxdb
      - INFLUXDB_USER=test
      - INFLUXDB_USER_PASSWORD=test123
    ports:
      - "8096:8086"  #http port
      - "8099:8089"  #udp port 
    #- "9088:9088"   
    volumes:
      - /data/influxdb/data:/var/lib/influxdb
      - /data/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: -config /etc/influxdb/influxdb.conf

  grafana:
    container_name: futurever-grafana-grafana
    restart: always
    image: futurever/grafana:5.1.0
    # environment: 
      # - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - /data/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - /data/grafana/log:/var/log/grafana
      # - /data/grafana/home:/usr/share/grafana
      # - /data/grafana/data:/var/lib/grafana
      # - /data/grafana/plugins:/var/lib/grafana/plugins
    command: -config /etc/grafana/grafana.ini
    depends_on: 
      - influxdb
