version: '3.2'
services:
  zookeeper:
    container_name: single-broker-zk
    image: wxcsdb88/zookeeper:3.4.13
    ports:
      - "2181:2181"
  kafka:
    container_name: zookeeper-kafka-kf
    image: wxcsdb88/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock